import re
import json
from typing import Literal, Optional, List
from litellm.integrations.custom_guardrail import CustomGuardrail
from litellm.types.utils import GenericGuardrailAPIInputs
from llm_guard.input_scanners import PromptInjection
from llm_guard.output_scanners import Sensitive

class EnterpriseThreatGuardrail(CustomGuardrail):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        # Scanner 1: Scan incoming prompts for injection attacks (0.80 threshold)
        self.input_injection_scanner = PromptInjection(threshold=0.80)
        # Scanner 2: Scan outgoing model completions for sensitive PII leaks
        self.output_sensitive_scanner = Sensitive(entity_types=["EMAIL_ADDRESS", "CREDIT_CARD", "US_SSN"])

    async def async_pre_call_hook(self, user_api_key_dict, cache, data, call_type):
        """Scans user prompts before sending requests to Ollama."""
        messages = data.get("messages", [])
        if not messages:
            return data

        user_prompt = messages[-1].get("content", "")
        sanitized_prompt, is_valid, risk_score = self.input_injection_scanner.scan(user_prompt)

        if not is_valid:
            raise Exception(f"Security Alert: Prompt injection detected (Risk Score: {risk_score})")

        return data

    async def async_post_call_hook(self, user_api_key_dict, response_data, data):
        """Scans response content generated by Ollama for PII exposure."""
        if "choices" in response_data and len(response_data["choices"]) > 0:
            content = response_data["choices"][0]["message"].get("content", "")
            sanitized_content, is_valid, risk_score = self.output_sensitive_scanner.scan(content)

            if not is_valid:
                response_data["choices"][0]["message"]["content"] = "[REDACTED: SENSITIVE INFORMATION DETECTED]"

        return response_data